spring:
  application:
    name: CodeSnippetBackendApplication
  datasource:
    username: root
    password: wu272515.
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.72.37.186:3306/snippet
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 3
      max-active: 20
      max-wait: 4000

token:
  secretKey: Y29kZSBzbmlwcGV0IHdlYnNpdGUgZm9yIGV2ZXJ5b25lIG9mIGRldmVsb3Blcg==
  expireTime: 2400000  # 40 * 60 * 1000 for 40min
#  expireTime: 10000
server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
